### ISSUE TITLE
Bug crash my app many times

### ISSUE THREAD

**Issue by amrashraf1992** [coolerfall/Android-HttpDownloadManager#78]
java.lang.ArrayIndexOutOfBoundsException: length=4096; regionStart=0; regionLength=-2
        at java.util.Arrays.checkOffsetAndCount(Arrays.java:135)
        at libcore.io.IoBridge.write(IoBridge.java:520)
        at java.io.RandomAccessFile.writeBytes(RandomAccessFile.java:544)
        at java.io.RandomAccessFile.write(RandomAccessFile.java:570)
        at com.coolerfall.download.DownloadDispatcher.executeDownload(DownloadDispatcher.java:246)
        at com.coolerfall.download.DownloadDispatcher.run(DownloadDispatcher.java:62)

**Comment by coolerfall** [comment]
Could you give more information, I didn't get this crash.

**Comment by amrashraf1992** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=4096; regionStart=0; regionLength=-2
        at java.util.Arrays.checkOffsetAndCount(Arrays.java:136)
        at libcore.io.IoBridge.write(IoBridge.java:547)
        at java.io.RandomAccessFile.writeBytes(RandomAccessFile.java:490)
        at java.io.RandomAccessFile.write(RandomAccessFile.java:518)
        at com.coolerfall.download.DownloadDispatcher.executeDownload(DownloadDispatcher.java:246)
        at com.coolerfall.download.DownloadDispatcher.updateFailure(DownloadDispatcher.java:157)
        at com.coolerfall.download.DownloadDispatcher.executeDownload(DownloadDispatcher.java:259)
        at com.coolerfall.download.DownloadDispatcher.run(DownloadDispatcher.java:62)

**Comment by amrashraf1992** [comment]
When i changed your library everything is good please help me

**Comment by amrashraf1992** [comment]
OkHttpClient client = new OkHttpClient.Builder().build();
        DownloadManager manager = new DownloadManager.Builder().context(MainActivity.getInstance())
                .downloader(OkHttpDownloader.create(client))
                .threadPoolSize(parallel_process)
                .logger(message -> Log.d("Download", message))
                .build();

        String[] URL = {"http://www.ovh.net/files/10Gb.dat","http://212.183.159.230/1GB.zip","http://speedtest-ny.turnkeyinternet.net/10000mb.bin"
                        ,"http://www.ovh.net/files/1Gb.dat","http://212.183.159.230/512MB.zip","https://cdn-eu-ep.azureedge.net/files/500mb.dat"};

        ArrayList<String> Files_Name = new ArrayList<>();

        for(int i = 0;i < parallel_files && i < URL.length;i++){
            try {
                long startTime = System.currentTimeMillis();

                Calendar calendar = Calendar.getInstance();
                Date now = calendar.getTime();
                String Name = new SimpleDateFormat("yyyyMMddHHmmss", Locale.US).format(now) + i;

                Files_Name.add(Name);

                String destPath = path + File.separator + Name;
                int finalI = i;
                DownloadRequest request =
                        new DownloadRequest.Builder()
                                .url(URL[i])
                                .retryTime(5)
                                .retryInterval(2, TimeUnit.SECONDS)
                                .progressInterval(1, TimeUnit.SECONDS)
                                .priority(com.coolerfall.download.Priority.HIGH)
                                .allowedNetworkTypes(DownloadRequest.NETWORK_MOBILE)
                                .destinationFilePath(destPath)
                                .downloadCallback(new DownloadCallback() {
                                    @Override
                                    public void onStart(int downloadId, long totalBytes) {
                                        JSONObject rootObject_out = new JSONObject();
                                        try {
                                            rootObject_out.put("TimeStamp", MainActivity.TimeFormat.format(Calendar.getInstance().getTime()));
                                            rootObject_out.put("Category", "Script");
                                            rootObject_out.put("title", "HTTP/HTTPS Download");
                                            rootObject_out.put("Subject", "Start");
                                            rootObject_out.put("Description", startTime - startTime_load);
                                            MainActivity.getInstance().data_out.put(rootObject_out);
                                        } catch (Exception e) {

                                        }
                                    }

                                    @Override
                                    public void onRetry(int downloadId) {
                                        JSONObject rootObject_out = new JSONObject();
                                        try {
                                            rootObject_out.put("TimeStamp", MainActivity.TimeFormat.format(Calendar.getInstance().getTime()));
                                            rootObject_out.put("Category", "Script");
                                            rootObject_out.put("title", "HTTP/HTTPS Download");
                                            rootObject_out.put("Subject", "Retry");
                                            rootObject_out.put("Description", "");
                                            MainActivity.getInstance().data_out.put(rootObject_out);
                                        } catch (Exception e) {

                                        }
                                    }

                                    @Override
                                    public void onProgress(int downloadId, long bytesWritten, long totalBytes) {
                                        float x = ((float) bytesWritten / (float) totalBytes) * 100;
                                        System.err.println(finalI + "--> " + bytesWritten + " / " + totalBytes + " / " + x);
                                    }

                                    @Override
                                    public void onSuccess(int downloadId, String filePath) {
                                        System.err.println("Done");
                                        Done_Array.add(true);

                                        File file = new File(filePath);

                                        long endTime = System.currentTimeMillis();

                                        float duration = (endTime - startTime) * 1000;
                                        float Speed = (file.length() * 8) / duration;
                                        duration = duration / (1000 * 1000);
                                        Log.v("Run", "=" + "HTTP Test Done......" + duration + "S " + Speed + "Mbps");

                                        JSONObject rootObject_out = new JSONObject();
                                        try {
                                            rootObject_out.put("TimeStamp", MainActivity.TimeFormat.format(Calendar.getInstance().getTime()));
                                            rootObject_out.put("Category", "Script");
                                            rootObject_out.put("title", "HTTP/HTTPS Download");
                                            rootObject_out.put("Subject", "Success");
                                            rootObject_out.put("Description", Speed);
                                            MainActivity.getInstance().data_out.put(rootObject_out);
                                        } catch (Exception ex) {

                                        }
                                    }

                                    @Override
                                    public void onFailure(int downloadId, int statusCode, String errMsg) {
                                        System.err.println("Failure");
                                        JSONObject rootObject_out = new JSONObject();
                                        try {
                                            rootObject_out.put("TimeStamp", MainActivity.TimeFormat.format(Calendar.getInstance().getTime()));
                                            rootObject_out.put("Category", "Script");
                                            rootObject_out.put("title", "HTTP/HTTPS Download");
                                            rootObject_out.put("Subject", "Failed");
                                            rootObject_out.put("Description", "Error in Session");
                                            MainActivity.getInstance().data_out.put(rootObject_out);
                                        } catch (Exception e) {

                                        }
                                        failed = true;
                                    }
                                })
                                .build();

                int id = manager.add(request);
                System.err.println("+++++++ " + id);
            }catch (Exception x){
                System.err.println("Failure");
                rootObject_out = new JSONObject();
                try {
                    rootObject_out.put("TimeStamp", MainActivity.TimeFormat.format(Calendar.getInstance().getTime()));
                    rootObject_out.put("Category", "Script");
                    rootObject_out.put("title", "HTTP/HTTPS Download");
                    rootObject_out.put("Subject", "Failed");
                    rootObject_out.put("Description", "Error in Session");
                    MainActivity.getInstance().data_out.put(rootObject_out);
                } catch (Exception e) {

                }
                failed = true;
            }
        }

**Comment by amrashraf1992** [comment]
this is bug only happened from 4 days unless i didn't change i thing in my code from a while

Is this issue related to internet problem if so please give me failure without crash :)

**Comment by coolerfall** [comment]
Did you give `WRITE_EXTERNAL_STORAGE` permission to your app?

**Comment by amrashraf1992** [comment]
@coolerfall Sure

**Comment by coolerfall** [comment]
Are you downloading large files? Check if you have enough space please.

**Comment by coolerfall** [comment]
Check v1.6.3
