### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by Terran-Marine** [coolerfall/Android-HttpDownloadManager#98]
先感谢大佬的库
下载过程中 会出现oom
`FATAL EXCEPTION: DownloadDispatcher
Process: PID: 25975
java.lang.OutOfMemoryError: Failed to allocate a 97436688 byte allocation with 25165824 free bytes and 89MB until OOM, target footprint 334048856, growth limit 402653184
	at com.android.tools.idea.protobuf.ByteString$Output.copyArray(ByteString.java:1076)
	at com.android.tools.idea.protobuf.ByteString$Output.flushLastBuffer(ByteString.java:1154)
	at com.android.tools.idea.protobuf.ByteString$Output.toByteString(ByteString.java:1070)
	at com.android.tools.appinspection.network.reporters.StreamReporter.onStreamClose(StreamReporter.kt:60)
	at com.android.tools.appinspection.network.trackers.InputStreamTracker.close(InputStreamTracker.kt:48)
	at okio.InputStreamSource.close(JvmOkio.kt:108)
	at okio.RealBufferedSource.close(RealBufferedSource.kt:477)
	at okhttp3.internal.Util.closeQuietly(Util.kt:495)
	at okhttp3.ResponseBody.close(ResponseBody.kt:192)
	at okhttp3.Response.close(Response.kt:302)
	at com.coolerfall.download.OkHttpDownloader.close(OkHttpDownloader.kt:79)
	at com.coolerfall.download.DownloadDispatcher.executeDownload(DownloadDispatcher.kt:240)
	at com.coolerfall.download.DownloadDispatcher.run(DownloadDispatcher.kt:52)`

**Comment by coolerfall** [comment]
这看着像是你用了appinspection工具造成的?

**Comment by Terran-Marine** [comment]
是的 确实在使用App Inspection .查看数据库时候出现.
